name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Только теги, начинающиеся с "v"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure tag is from master branch
        run: |
          BRANCH=$(git branch -r --contains "$GITHUB_SHA" | grep origin/master || true)
          if [ -z "$BRANCH" ]; then
            echo "Tag not from master branch. Skipping..."
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            gjiuxapb/superset:${{ steps.extract_tag.outputs.TAG }}
            gjiuxapb/superset:latest
